const sentences = [
    "Sunsets bring peace to the heart",
    "Coding sparks creativity and innovation",
    "Books open new worlds of imagination",
    "Kindness is a language everyone understands",
    "Coffee fuels the morning energy burst",
    "Dream big work hard stay humble",
    "Nature heals the soul profoundly",
    "Love deeply forgive freely live fully",
    "Chase dreams not perfection",
    "Explore the beauty of life daily",
    "Smile often its contagious",
    "Laughter is lifes sweet melody",
    "Create joy with every step",
    "Balance is the key to harmony",
    "Breathe deeply find calmness within",
    "Adventure awaits around every corner",
    "Stay curious embrace learning always",
    "Happiness blooms from a grateful heart",
    "Gratitude transforms ordinary days",
    "Live authentically be yourself",
    "Act kindly impact lives positively",
    "Think freely let ideas soar",
    "Inspire others with your actions",
    "Persist in the face of challenges",
    "Believe in yourself magic happens",
    "Celebrate victories big and small",
    "Life is short make it sweet",
    "Tomorrow is a new beginning",
    "Positive vibes attract positive outcomes",
    "Find joy in the little things",
    "Mindfulness brings peace within chaos",
    "Dreamers create their own reality",
    "Explore discover and experience life",
    "Seize opportunities create your fate",
    "Adventure begins outside your comfort zone",
    "Success is born from consistent effort",
    "Cherish moments create memories forever",
    "Radiate positivity in every encounter",
    "Learn grow evolve constantly",
    "Progress over perfection every time",
    "Innovate disrupt leave a legacy",
    "Stay focused on your unique journey",
    "Lifes best moments are unexpected",
    "Dance in the rain of life",
    "Leap the net will appear",
    "Smile its your superpower",
    "Rainy days bring cozy moments",
    "Success requires hard work consistently",
    "Find beauty in ordinary moments",
    "Dream big act bigger",
    "Challenge shapes who you become",
    "Savor the sweetness of success",
    "Tomorrows success begins today",
    "Risk leads to the greatest rewards",
    "Chase your passion relentlessly",
    "Believe you are capable always",
    "Endless possibilities surround you daily",
    "Effort transforms dreams into reality",
    "Imagine create believe achieve",
    "Start small dream big always",
    "Your journey defines your destination",
    "Lifes rhythm is found in balance",
    "Embrace change it brings growth",
    "Every end is a new beginning",
    "Cultivate a garden of gratitude",
    "Live fully laugh often love deeply",
    "Every day is a fresh start",
    "Inspiration fuels creative brilliance",
    "Success is a journey not destination",
    "You are your only limit",
    "The universe conspires for you",
    "Act boldly amazing things happen",
    "Radiate kindness create ripples endlessly",
    "Persist the breakthrough is near",
    "Sunshine follows even the darkest nights",
    "Chase sunsets embrace serenity",
    "Unleash the power within you",
    "Find strength in adversity always",
    "Tomorrow is another opportunity",
    "Cultivate resilience endure and overcome",
    "Celebrate the unique in you",
    "Magic happens outside comfort zones",
    "Persevere it builds character enduringly",
    "Silence speaks volumes in chaos",
    "Focus on progress not perfection",
    "Inspire through your authentic actions",
    "Adventure fuels the souls fire",
    "Kind hearts create lasting impact",
    "Let go new beginnings await",
    "Discover joy in simple pleasures",
    "Breathe deeply calm your soul",
    "Success is an ongoing journey",
    "Chase dreams embrace the adventure",
    "Positivity attracts endless possibilities",
    "Create innovate leave an imprint",
    "Embrace change it breeds growth",
    "Radiate love it transforms everything",
    "Find beauty in ordinary moments",
    "Dreamers create their own reality",
    "Seize opportunities create your fate",
    "Adventure begins outside your comfort zone",
    "Success is born from consistent effort",
    "Cherish moments create memories forever",
    "Radiate positivity in every encounter",
    "Learn grow evolve constantly",
    "Progress over perfection every time",
    "Innovate disrupt leave a legacy",
    "Stay focused on your unique journey",
    "Lifes best moments are unexpected",
    "Dance in the rain of life",
    "Leap the net will appear",
    "Smile its your superpower",
    "Rainy days bring cozy moments",
    "Success requires hard work consistently",
    "Find beauty in ordinary moments",
    "Dream big act bigger",
    "Challenge shapes who you become",
    "Savor the sweetness of success",
    "Tomorrows success begins today",
    "Risk leads to the greatest rewards",
    "Chase your passion relentlessly",
    "Believe you are capable always",
    "Endless possibilities surround you daily",
    "Effort transforms dreams into reality",
    "Imagine create believe achieve",
    "Start small dream big always",
    "Your journey defines your destination",
    "Lifes rhythm is found in balance",
    "Embrace change it brings growth",
    "Every end is a new beginning",
    "Cultivate a garden of gratitude",
    "Live fully laugh often love deeply",
    "Every day is a fresh start",
    "Inspiration fuels creative brilliance",
    "Success is a journey not destination",
    "You are your only limit",
    "The universe conspires for you",
    "Act boldly amazing things happen",
    "Radiate kindness create ripples endlessly",
    "Persist the breakthrough is near",
    "Sunshine follows even the darkest nights",
    "Chase sunsets embrace serenity",
    "Unleash the power within you",
    "Find strength in adversity always",
    "Tomorrow is another opportunity",
    "Cultivate resilience endure and overcome",
    "Celebrate the unique in you",
    "Magic happens outside comfort zones",
    "Persevere it builds character enduringly",
    "Silence speaks volumes in chaos",
    "Focus on progress not perfection",
    "Inspire through your authentic actions",
    "Adventure fuels the souls fire",
    "Kind hearts create lasting impact",
    "Let go new beginnings await",
    "Discover joy in simple pleasures",
    "Breathe deeply calm your soul",
    "Success is an ongoing journey",
    "Chase dreams embrace the adventure",
    "Positivity attracts endless possibilities",
    "Create innovate leave an imprint",
    "Embrace change it breeds growth",
    "Radiate love it transforms everything"
];