const sentences=["Go down",
"It doesnt matter",
"Plucking flowers is prohibited",
"We both like each other",
"Whats your phone number",
"A set of books is on the table",
"May God bless you",
"This is not fair",
"I hate you",
"Its for the best",
"I talked with him",
"What is your contact number",
"What do you want to do",
"Are you there",
"Write with an improved hand",
"What would you like to have",
"Forget it",
"Who will cooperate with you",
"It was nice to talk with you",
"Can you please repeat that",
"As soon as possible",
"You are a glutton",
"When will you reach",
"Call me back",
"The terms were finalized",
"Improve your handwriting",
"Whats your name",
"See you",
"The matter is clear",
"I appreciate it",
"What did you say",
"Be calm",
"How much is that",
"What can I do for you",
"I hope you understand",
"Do you have some money",
"Whats the time by your watch",
"I wish you a happy married life",
"Do you need anything",
"I dont know telling a lie",
"I invited him to tea",
"Many happy returns of the day",
"Dont worry",
"How are things going",
"What do we call this in English",
"This is not a joke",
"I hope so",
"I dont want to",
"Which date falls on Sunday",
"I am very pleased to meet you",
"Watch out",
"Do you want to join me",
"One has to pass the time anyhow",
"I will catch you soon",
"Dont move",
"Dont do this",
"We do not travel first class",
"Please be seated",
"Let it be",
"Allow me to introduce myself",
"He looks rather nervous",
"What is your problem",
"Please help yourself",
"Doesnt matter",
"Its up to you",
"Put the books in order",
"I will call you later",
"I decline that",
"Come what may I will not talk to him",
"The examination will start on Monday",
"Thank you for inviting us",
"How disgusting",
"Are you coming",
"India must stop being the follower",
"Could you stay away from my stuff",
"Yes, by all means",
"I have no idea",
"Have you wound the watch",
"I am feeling tired today",
"Sorry for the inconvenience",
"How dare you",
"Lets catch up",
"Why are you upset",
"Good day to you, Sir",
"Follow me",
"You turn",
"He owes the shopkeeper fifty rupees",
"What a bother",
"Do me a favor",
"We will break but not bend",
"Get out of my sight",
"Have a good trip",
"Rest assured",
"This doesnt behoove you",
"What do you want from me",
"Come with me",
"I have to leave early today",
"He had a narrow escape",
"What are your likes and dislikes",
"What are you talking about",
"Join me",
"I have no alternative",
"I feel much better",
"Do I have to",
"The examination is on my head",
"Enjoy yourself",
"Didnt you go to the cinema yesterday",
"May you succeed",
"Its my pleasure",
"Please come as soon as possible",
"He became bankrupt",
"I will try my level best",
"What nonsense",
"Dont be ridiculous",
"Every moment weighed heavily on him",
"I did not understand",
"Where are you from",
"I got it",
"I wish you well",
"Everything is fine",
"Are you kidding",
"Good morning",
"I dropped in casually",
"Daily exercise makes you fit and healthy",
"God bless you",
"I do not understand",
"Whatever he says is not true",
"Do you speak English",
"Dont be so childish",
"Im sorry",
"I dont have a single paisa",
"Read the sentences carefully",
"Thats so kind of you",
"Good heavens",
"Its none of your business",
"I beg your pardon",
"Its all yours",
"How disgraceful",
"Im at the office",
"He had no money",
"His words have weight",
"Would you please speak slowly",
"Wonderful",
"What are you doing",
"Rod is the logic of fools",
"A crease is formed on the cloth",
"Call me any day",
"I shall reach by 530 train",
"What are you doing today",
"Go up",
"Its very thoughtful of you",
"The temperature will come down tomorrow",
"I dont know",
"No, I dont want it",
"But he did not budge an inch",
"Excuse me",
"Do you understand me",
"There is something wrong with his brain",
"You are my responsibility",
"As you please",
"Well done, dear",
"Where are you",
"How can I go to the town center",
"He has a nasal accent",
"Can I ask you something",
"Im at home",
"The soil of that place is fertile",
"Who is your favorite teacher",
"How old are you",
"I decline",
"Hurry up otherwise, you will miss the train",
"I missed my school bus",
"Can I help you",
"I dont need your advice",
"The holidays will begin on 10th May",
"I will come again",
"Do you know what I mean",
"I apologize for being late",
"My room is on the second floor",
"Will you please help me with this",
"You are wasting my time",
"I have a house to live in",
"Thank you for the advice",
"Come on",
"I dont eat nonveg on Tuesday",
"By whom is he being treated",
"Are you joining us",
"Cheer up",
"It really takes time",
"It is a matter of sorrow",
"Why are you late",
"Slow down your car",
"Im sorry",
"The is fit for marriage",
"Did you get it",
"I cant believe it",
"You have no match",
"What is happening here",
"I knew it",
"Kneel and give thanks to God",
"What do you mean",
"Im sorry I cant assist you",
"See you next time",
"Dont involve me in this matter",
"Do you agree with me",
"Whats your email address",
"Good night",
"That is against me",
"Have a nice day",
"I am tired",
"Believe me",
"You should eat a little less",
"Im on my way",
"See you next time",
"Have a good time",
"He has a bad headache",
"It was nice meeting you",
"What do you need",
"His luck took a turn",
"Get ready to go to school",
"Could you help me",
"I just made it",
"My watch is out of order",
"How are you",
"Are you done",
"All worship the rising sun",
"Stop making so much noise",
"I dont have time",
"These two are more or less alike",
"She wakes early in the morning",
"I admire you",
"Are you married all",
"What is done is done",
"Please say something",
"I dont have time",
"Good afternoon",
"Whom do you suspect",
"We cook everyday",
"Absolutely not",
"Give me a hand",
"He has a mild fever",
"Hope to see you next time",
"Im good at my work",
"I do not mean it",
"I did as I was told",
"You are getting late for school",
"Im on a diet",
"Thank you very much",
"How much do I owe you",
"Its ok for him, isnt it",
"I am busy",
"This work is not suitable for you",
"They like each other",
"The house was decorated",
"Try to open this door",
"Not yet",
"I love you",
"He was tired of running about",
"He sleeps in the afternoon",
"I cant wait any longer",
"Slow down",
"Try a little selfcontrol",
"I love to play video games",
"Nice to meet you",
"Im good",
"The train came on time",
"Talk to you tomorrow",
"I could see through the matter",
"Are you fooling me",
"Nice to meet you",
"Hurry up",
"Is everything ok",
"What time does the next train leave",
"He is still not well",
"What are you up to",
"I would love to",
"Fetch water from the well",
"How can I help you",
"What are your hobbies",
"I apologize",
"It has rained excessively today",
"Could you give me some money",
"Whats the weather like",
"You are going too fast",
"Its a good beginning",
"This is your updated version",
"How much is it",
"Any day will do",
"He is serving his own ends",
"I feel sad about your loss",
"Oh, I am sorry I have got a bit late",
"Of Course",
"Just shut up for a minute",
"She abused me",
"Will you now beat him to death",
"Where did you get it",
"Speak what is true",
"I do not want to know anything",
"Do come",
"How long will you stay",
"Please credit this amount to my account",
"Talk to you later",
"Rest assured",
"I cannot agree with your opinions",
"You have bought me to shame",
"Well done Keep it up",
"Anything else",
"Stop making such a noise",
"Walk carefully",
"Go slow from the crowd",
"How do you feel",
"I am very strict on this matter",
"I read books",
"I just made it",
"Give me a day",
"What do you like the most",
"I am busy at the moment",
"I agree",
"It has to be done",
"What is your favorite subject",
"I cant wait",
"All my calculations went wrong",
"Girls do not want to stay in the gum",
"Be quiet",
"Come with me",
"He scored a goal in the match",
"The sun rises from the east",
"Be careful",
"Shut up",
"Go if you can",
"Drive carefully",
"Forgive me",
"God bless you",
"The time has come",
"Do not disturb",
"Come what may",
"Is all good",
"He crushed my hopes",
"Please give me your hand",
"Get Off",
"How was your weekend",
"I will move heaven and earth",
"Come quickly",
"I dont agree",
"What do you want",
"Please write down this address",
"Stop kidding",
"Are you sure",
"No, I dont want",
"It is a strange thing",
"Could you show me your answer sheet",
"Im sorry to interrupt you",
"Allow me",
"Will you go there or shall I",
"I made it",
"How can I go to the city",
"Do me a favor",
"I like fairly hot tea",
"Is everything alright",
"Can you turn the volume up",
"What do you think",
"What did you succeed in",
"Where are you going",
"I dont need you",
"Your name is on the list",
"Happy birthday",
"Not the least",
"What is going on",
"The advantages of this are many",
"I am sorry",
"A lovely day, isnt it",
"Let us see where he stands",
"Where is your office",
"Youre driving too fast",
"Have a good weekend",
"I said many things to him",
"Stop crying",
"When is the train leaving",
"Its on the tip of my tongue",
"I dont like tall talks",
"I have completed my homework",
"Are you coming with me",
"Im on a diet",
"He tells a lie",
"Who is your class teacher",
"By Gods Grace",
"Lets do it",
"You will not be able to deal with him",
"He will not refrain from speaking",
"Do as I say",
"What is your job",
"My mind is reeling",
"Did you get my point",
"Where do you live",
"I have a lot to talk about",
"Lets celebrate",
"Hows it going",
"How have you been",
"Hows your family",
"Whats up",
"Whats new",
"Pretty good",
"Cant complain",
"Ive been busy",
"Thanks a lot",
"I really appreciate it",
"Would you like a drink",
"How do you feel about",
"Im returning your call",
"Can you tell me…",
"Would you happen to know…",
"I have no idea",
"Im not really sure",
"Thats OK",
"I am not accepting anything else at this time",
"Im not ready yet",
"Ill pay",
"I dont want that",
"Hows work going",
"Dont take it personally",
"It was the least I could do",
"Youre the light of my life",
"Im not sure",
"Ill take it",
"I dont want to bother you",
"Hurry",
"Dont worry",
"No problem",
"Youre everything to me",
"Im sorry, were sold out",
"Ill take you to the bus stop",
"I feel good",
"I am dog tired",
"Everyone knows it",
"Im divorced",
"I adore you",
"Im thirsty",
"Im an American",
"I get off of work at 6",
"I am starving",
"Everything is ready",
"Im single",
"I miss your laugh",
"Im very busy I dont have time now",
"Im cleaning my room",
"I have a headache",
"I cant complain",
"From time to time",
"Id like you to meet…",
"Whats up",
"Im not married",
"Ill come back later",
"I dont want it",
"How are you",
"Chicago is very different from Boston",
"Im planning to…",
"You occupy my thoughts",
"It cost me a fortune",
"Im cold",
"I hope you and your wife have a nice trip",
"I couldnt agree more",
"Good idea",
"It was nice chatting with you",
"What are you up to these days",
"Im not busy",
"Ill call you when I leave",
"I dont understand",
"How are you doing today",
"Can you translate this for me",
"No, thanks Im OK",
"You are my reason for living",
"Long time no see",
"Im coming to pick you up",
"I know",
"I ate already",
"He likes it very much",
"Is it in fact the case that…",
"You inspire me",
"Thank you so much",
"Im going to leave",
"I like her",
"I cant hear you",
"Help",
"Dont you think that…",
"I feel sad without you",
"That is dirt cheap",
"Im good, and you",
"I lost my watch",
"I dont know how to use it",
"Hes coming soon",
"Do you see what I mean",
"I appreciate you",
"Thats a good one",
"Im happy",
"I love you",
"I dont like him",
"Hes right",
"Phrases for Telephone Calls",
"We will be having a good time",
"Im married",
"If you need my help, please let me know",
"I dont speak very well",
"Hes very famous",
"Break a leg",
"You crossed my mind",
"The scorching sun",
"Im hungry",
"Id like to go for a walk",
"I dont like it",
"Hes very annoying",
"Beats me",
"Be careful driving"];